// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/work-team/update/{teamCode}": {
            "put": {
                "description": "Update a work team based on teamCode",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "work-team"
                ],
                "summary": "Update work team",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team code",
                        "name": "teamCode",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated work team",
                        "name": "team",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.WorkTeam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse-models_WorkTeam"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse-models_WorkTeam"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse-models_WorkTeam"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ApiResponse-models_WorkTeam": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Response data",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.WorkTeam"
                        }
                    ]
                },
                "message": {
                    "description": "Descriptive message",
                    "type": "string",
                    "example": "Successful operation"
                },
                "status": {
                    "description": "Response status",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "models.WorkTeam": {
            "description": "Structure representing a work team",
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "Team responsible for software development"
                },
                "members": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[\"user1\"",
                        " \"user2\"]"
                    ]
                },
                "status": {
                    "type": "boolean",
                    "example": true
                },
                "team_code": {
                    "type": "string",
                    "example": "TEAM-001"
                },
                "team_name": {
                    "type": "string",
                    "example": "Development Team"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "work_team_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8182",
	BasePath:         "",
	Schemes:          []string{"http", "https"},
	Title:            "Work Team Update API",
	Description:      "API for managing work teams.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
